PROGS := camera_display.c
# PROGS := 1-pin-setup.c

# COMMON_SRC += ov7670_init.c
COMMON_SRC += ov7670_staff.c
COMMON_SRC += mbox.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

include $(CS340LX_2025_PATH)/libpi/mk/Makefile.robust
