PROGS = 1-dma-blink.c
PROGS = 0-dma-example.c

COMMON_SRC := 

# if you need to override the install
BOOTLOADER = my-install

OPT_LEVEL = -Og

# automatically run the code
RUN = 1

LIBS += $(CS340LX_2025_PATH)/lib/libgcc.a
LIB_POST += $(CS340LX_2025_PATH)/lib/libgcc.a

include $(CS340LX_2025_PATH)/libpi/mk/Makefile.robust
